version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: easygifts-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EasyGiftsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easygifts-api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__MyPostgreDB: "Host=postgres;Port=5432;Database=EasyGiftsDb;Username=postgres;Password=postgres"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend/easygifts-front
      dockerfile: Dockerfile
    container_name: easygifts-frontend
    depends_on:
      - api
    ports:
      - "4200:80"

volumes:
  pgdata:
