services:
  postgres:
    image: postgres:17
    container_name: easygifts-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EasyGiftsDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easygifts-api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__MyPostgreDB: "Host=postgres;Port=5432;Database=EasyGiftsDb;Username=postgres;Password=postgres"
      ASPNETCORE_URLS: "http://+:5000"
      Smtp__Host: "sandbox.smtp.mailtrap.io"
      Smtp__Port: "587"
      Smtp__Username: "5bcb9d4735db38"
      Smtp__Password: "606c94d8d3d408"
      Smtp__From: "EasyGifts <dev@easygifts.local>"
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: src/EasyGifts.Web/Dockerfile
    container_name: easygifts-web
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  pgdata:
